#!/usr/bin/php
<?php
require_once __DIR__ . '/../../vendor/autoload.php';
$config_filename = getenv('FINXLOG_ROOT_PATH') . '/www/js/config_autobuild.js';
assert(strlen(getenv('FINXLOG_ENV_JS')));
$front_param_list = array_filter(
        preg_split(
        '~[\s,;]+~us',
        getenv('FINXLOG_ENV_JS')
    )
);

$front_param = [];
foreach ($front_param_list as $param) {
    if (getenv($param) === false) {
        continue;
    }
    $front_param[$param] = getenv($param);
}

file_put_contents(
    $config_filename,
    "//DO NOT EDIT THIS FILE.\n//Build it with composer update\n"
    . "FinXLog.config ="
    . json_encode($front_param, getenv('FINXLOG_DEBUG') ? JSON_PRETTY_PRINT : null)
    . ";\nFinXLog.start();\n"
);
